server:
  port: 8080

spring:
  application:
    name: mauresto-backend
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
